services:
    spring-db:
        image: postgres:alpine
        container_name: FinTech-DB
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=05102021
          - POSTGRES_DB=FinTech
          - PGPORT=5432
        command: postgres -c 'max_connections=1000'
        ports:
            - 5433:5432
        expose:
            - 5433
        volumes:
            - fin-tech-volume:/var/lib/postgresql
        networks:
            - test-networks

    spring-boot:
        image: valapp.fin-tech-volume
        container_name: val.fin-tech-volume
        build:
            context: .
        ports:
            - 6500:6500
        links:
          - spring-db
        depends_on:
            - spring-db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:spring-db://localhost:5433/FinTech
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=05102021
        networks:
            - test-networks        
volumes:
    fin-tech-volume:

networks:
    test-networks:
        driver: bridge